In [33]:
using  LinearAlgebra

In [47]:
# tensor with randomly generated entries, order 3, dims: 2-by-3-by-4
A = rand(2,2,2,2)

# identity matrix, order 2, dims: 5-by-5 (New syntax in Julia 0.7+)
B = Matrix{Float64}(I,5,5)

# tensor of 1's, order 4, dims: 2-by-4-by-2-by-4
C = ones(2,4,2,4)

# matrix of 0's, order 2, dims: 3-by-5
D = zeros(3,5)

# initialize complex random tensor
E = rand(2,3,4) + im*rand(2,3,4)

2×3×4 Array{ComplexF64, 3}:
[:, :, 1] =
 0.165591+0.251636im  0.644302+0.602742im  0.0600068+0.31263im
 0.828311+0.376073im  0.539378+0.267011im   0.789551+0.635325im

[:, :, 2] =
 0.442118+0.31687im    0.979493+0.630683im  0.129503+0.247684im
 0.153653+0.624393im  0.0581962+0.336925im  0.643536+0.830689im

[:, :, 3] =
 0.312534+0.138524im  0.857637+0.0249971im  0.743156+0.572422im
   0.4078+0.30835im   0.425667+0.351313im   0.872847+0.134218im

[:, :, 4] =
 0.994906+0.908168im  0.540337+0.1507im     0.96376+0.0574168im
 0.628439+0.896419im  0.439377+0.245981im  0.897256+0.279732im

In [48]:
A

2×2×2×2 Array{Float64, 4}:
[:, :, 1, 1] =
 0.277708  0.746711
 0.729846  0.355048

[:, :, 2, 1] =
 0.877473  0.479074
 0.702642  0.985343

[:, :, 1, 2] =
 0.0712672  0.770615
 0.247541   0.916366

[:, :, 2, 2] =
 0.609669  0.567796
 0.868187  0.394204

In [50]:
#(a):Permute

Atilda = permutedims(A,[4,1,2,3])

2×2×2×2 Array{Float64, 4}:
[:, :, 1, 1] =
 0.277708   0.729846
 0.0712672  0.247541

[:, :, 2, 1] =
 0.746711  0.355048
 0.770615  0.916366

[:, :, 1, 2] =
 0.877473  0.702642
 0.609669  0.868187

[:, :, 2, 2] =
 0.479074  0.985343
 0.567796  0.394204

In [51]:
#Ex.1.2(b):Reshape
F = rand(4,4,4)


4×4×4 Array{Float64, 3}:
[:, :, 1] =
 0.106151    0.139222   0.667462  0.158117
 0.311851    0.540077   0.161437  0.820401
 0.722408    0.826174   0.973885  0.01622
 0.00192776  0.0976027  0.949946  0.571774

[:, :, 2] =
 0.67071   0.438392   0.613269   0.193103
 0.601435  0.0663519  0.0581607  0.935538
 0.117616  0.595179   0.715785   0.801244
 0.243257  0.435714   0.517485   0.625965

[:, :, 3] =
 0.574799  0.994454  0.619886  0.661915
 0.492719  0.562479  0.55107   0.187201
 0.117592  0.144035  0.484073  0.699052
 0.687268  0.640768  0.860211  0.466031

[:, :, 4] =
 0.474136    0.519981  0.224578  0.26127
 0.50741     0.429663  0.37324   0.0796418
 0.00476318  0.213509  0.933826  0.126983
 0.511375    0.549488  0.57158   0.830939

In [52]:
Ftilda = reshape(F,4,4^2)

4×16 Matrix{Float64}:
 0.106151    0.139222   0.667462  0.158117  …  0.519981  0.224578  0.26127
 0.311851    0.540077   0.161437  0.820401     0.429663  0.37324   0.0796418
 0.722408    0.826174   0.973885  0.01622      0.213509  0.933826  0.126983
 0.00192776  0.0976027  0.949946  0.571774     0.549488  0.57158   0.830939

In [39]:
B

5×5 Matrix{Float64}:
 1.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  0.0  1.0

In [27]:
C

2×4×2×4 Array{Float64, 4}:
[:, :, 1, 1] =
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0

[:, :, 2, 1] =
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0

[:, :, 1, 2] =
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0

[:, :, 2, 2] =
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0

[:, :, 1, 3] =
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0

[:, :, 2, 3] =
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0

[:, :, 1, 4] =
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0

[:, :, 2, 4] =
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0

In [28]:
D

3×5 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [29]:
E

2×3×4 Array{ComplexF64, 3}:
[:, :, 1] =
 0.920221+0.733649im  0.259806+0.155091im  0.324937+0.268052im
 0.908375+0.167759im  0.572553+0.212141im  0.622921+0.37346im

[:, :, 2] =
  0.74911+0.179685im  0.267182+0.150828im  0.892594+0.760507im
 0.693063+0.840593im  0.169604+0.157123im  0.885387+0.291739im

[:, :, 3] =
 0.305158+0.989258im  0.972669+0.0967278im  0.956044+0.271808im
 0.921743+0.124701im  0.071563+0.748437im   0.702787+0.631027im

[:, :, 4] =
  0.70197+0.461671im  0.376339+0.637053im  0.441083+0.692087im
 0.343216+0.6861im     0.24206+0.339027im  0.445131+0.234091im

In [64]:
##### Ex.1.3(a): Binary Tensor Contraction
d = 2;
A = rand(d,d,d,d);  B = rand(d,d,d,d);

Ap  = permutedims(A,[1,3,2,4]);  Bp  = permutedims(B,[1,4,2,3]);
Apr = reshape(Ap,d^2,d^2);       Bpr = reshape(Bp,d^2,d^2);
Cpr = Apr*Bpr;
C   = reshape(Cpr,d,d,d,d);

In [65]:
A

2×2×2×2 Array{Float64, 4}:
[:, :, 1, 1] =
 0.57302   0.452972
 0.560062  0.409988

[:, :, 2, 1] =
 0.0384126  0.220683
 0.737094   0.748078

[:, :, 1, 2] =
 0.15734    0.224047
 0.0832772  0.386661

[:, :, 2, 2] =
 0.15758    0.485937
 0.0108616  0.745074

In [66]:
Ap

2×2×2×2 Array{Float64, 4}:
[:, :, 1, 1] =
 0.57302   0.0384126
 0.560062  0.737094

[:, :, 2, 1] =
 0.452972  0.220683
 0.409988  0.748078

[:, :, 1, 2] =
 0.15734    0.15758
 0.0832772  0.0108616

[:, :, 2, 2] =
 0.224047  0.485937
 0.386661  0.745074

In [67]:
Apr

4×4 Matrix{Float64}:
 0.57302    0.452972  0.15734    0.224047
 0.560062   0.409988  0.0832772  0.386661
 0.0384126  0.220683  0.15758    0.485937
 0.737094   0.748078  0.0108616  0.745074

In [68]:
##### Ex.1.4(c): Tensor network evaluation
d = 10; A = rand(d,d);  B = rand(d,d); C = rand(d,d);
# Evaluare network via summation over internal indices
F0 = zeros(d,d);
for id = 1:d
    for jd = 1:d
        for kd = 1:d
            for ld = 1:d
                F0[id,jd] = F0[id,jd] + A[id,kd]*B[kd,ld]*C[ld,jd];
            end
        end
    end
end
# Evaluare network via sequence of binary contractions
F1 = (A*B)*C;

In [69]:
F0

10×10 Matrix{Float64}:
 13.3556  13.6591  13.8175  14.9754  …  14.1626  13.2207  12.7631  11.8092
 18.9098  18.2819  19.4986  20.2868     19.5244  17.5583  16.8754  16.124
 13.3292  12.6883  13.4362  13.9129     13.0947  11.9928  11.6895  10.6166
 12.7182  12.0331  13.1903  13.2666     13.1267  11.4115  11.1896  10.6444
 18.0231  17.9012  18.5292  19.6909     18.7387  17.1452  16.5635  15.479
 16.4281  16.2641  17.0397  17.8021  …  17.1897  15.4947  15.2561  14.3514
 11.2926  11.1745  11.849   12.4043     12.2778  10.7277  10.7109  10.1734
 18.9511  18.3191  19.1869  20.0251     19.5669  17.2231  17.0091  15.8655
 25.3841  24.3852  26.0169  27.0112     26.5055  23.1457  22.7751  21.7335
 14.057   13.6226  14.0319  14.9117     14.553   12.6891  13.1878  11.9568

In [70]:
F1

10×10 Matrix{Float64}:
 13.3556  13.6591  13.8175  14.9754  …  14.1626  13.2207  12.7631  11.8092
 18.9098  18.2819  19.4986  20.2868     19.5244  17.5583  16.8754  16.124
 13.3292  12.6883  13.4362  13.9129     13.0947  11.9928  11.6895  10.6166
 12.7182  12.0331  13.1903  13.2666     13.1267  11.4115  11.1896  10.6444
 18.0231  17.9012  18.5292  19.6909     18.7387  17.1452  16.5635  15.479
 16.4281  16.2641  17.0397  17.8021  …  17.1897  15.4947  15.2561  14.3514
 11.2926  11.1745  11.849   12.4043     12.2778  10.7277  10.7109  10.1734
 18.9511  18.3191  19.1869  20.0251     19.5669  17.2231  17.0091  15.8655
 25.3841  24.3852  26.0169  27.0112     26.5055  23.1457  22.7751  21.7335
 14.057   13.6226  14.0319  14.9117     14.553   12.6891  13.1878  11.9568

In [73]:
@benchmark F1*20

LoadError: LoadError: UndefVarError: @benchmark not defined
in expression starting at In[73]:1

In [74]:
using BanchmarkTools

LoadError: ArgumentError: Package BanchmarkTools not found in current path:
- Run `import Pkg; Pkg.add("BanchmarkTools")` to install the BanchmarkTools package.


In [78]:
import Pkg.add(BanchmarkTools)

LoadError: syntax: extra token "(" after end of expression

In [80]:
@benchmark  F1 = (A*B)*C

LoadError: LoadError: UndefVarError: @benchmark not defined
in expression starting at In[80]:1

In [81]:
##### Ex.1.4(c): Tensor network evaluation
d = 10; A = rand(d,d);  B = rand(d,d); C = rand(d,d);
# Evaluare network via summation over internal indices
F0 = zeros(d,d);
for id = 1:d
    for jd = 1:d
        for kd = 1:d
            for ld = 1:d
                F0[id,jd] = F0[id,jd] + A[id,kd]*B[kd,ld]*C[ld,jd];
            end
        end
    end
end

In [88]:
 @profile macro 

LoadError: syntax: incomplete: premature end of input

In [89]:
using BenchmarkTools

In [90]:
@benchmark (F1 = (A*B)*C)

BenchmarkTools.Trial: 10000 samples with 133 evaluations.
 Range (min … max):  704.248 ns …   6.291 μs  ┊ GC (min … max): 0.00% … 86.66%
 Time  (median):     733.951 ns               ┊ GC (median):    0.00%
 Time  (mean ± σ):   788.624 ns ± 350.506 ns  ┊ GC (mean ± σ):  2.99% ±  6.09%

  ▅▄█▅▆▂       ▁                                                ▁
  █████████▆▇████▇▆▇▆▆▅▅▅▆▇█▇█▆▅█▄▅▇▆▆▆▆▆▅▅▅▅▅▅▄▅▃▅▆▅▃▃▃▃▃▃▄▄▄▄ █
  704 ns        Histogram: log(frequency) by time       1.39 μs <

 Memory estimate: 1.75 KiB, allocs estimate: 2.

In [91]:
@benchmark (F1 = A*(B*C))

BenchmarkTools.Trial: 10000 samples with 143 evaluations.
 Range (min … max):  719.587 ns …   7.389 μs  ┊ GC (min … max): 0.00% … 88.15%
 Time  (median):     745.378 ns               ┊ GC (median):    0.00%
 Time  (mean ± σ):   796.926 ns ± 392.375 ns  ┊ GC (mean ± σ):  3.43% ±  6.30%

  █▇█▇▂     ▁ ▁                                                 ▂
  ██████▇▇▅▇█████▆▇▆▆▆▆▇▇██▇▆█▆▆█▆▆█▇▆▆▅▆▅▅▄▆▅▄▆▆▅▄▅▆▄▅▄▅▄▆▆▄▃▃ █
  720 ns        Histogram: log(frequency) by time       1.37 μs <

 Memory estimate: 1.75 KiB, allocs estimate: 2.